name: EKS Cluster Deployment to k8s
on:
  push:
    branches:
      - master

jobs:
  eks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        run: echo "Preparing for EKS cluster deployment..."

      - name: Update Computer
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.24.0' # default is latest stable
        id: install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: update-testing
          VERSION: 1
          USERNAME: syjjem093
        run: |
          docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
          docker push $USERNAME/$IMAGE_NAME:$VERSION


      - name: Update kube config
        run: aws eks update-kubeconfig --name cluster-1
            

      # - name: Install Helm
      #   run: |
      #     helm template project project
      #     helm install project project

      # - name: Install Prometheus
      #   run: |
      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      #     helm repo add stable https://charts.helm.sh/stable
      #     helm repo update
      #     helm install prometheus prometheus-community/prometheus
     
      - name: Deploy to EKS
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml

      
      